controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      state_publish_rate: 50
      command_interfaces:
        - position
      state_interfaces:
        - position
      gains:
        joint1:
          p: 100.0
          d: 10.0
        joint2:
          p: 100.0
          d: 10.0
        joint3:
          p: 100.0
          d: 10.0
        joint4:
          p: 100.0
          d: 10.0
        joint5:
          p: 100.0
          d: 10.0
        joint6:
          p: 100.0
          d: 10.0

